### ISSUE TITLE
Test Google Firestore connection within China

### ISSUE THREAD

**Issue by RichardeJiang** [RichardeJiang/from_android#3]
Firestore integration is done in commit https://github.com/RichardeJiang/from_android/commit/c9487b9678de6b972c028bfdb38e1e1b28f00e54 although the project was setup in Asia:east region, we may still want to check the feasibility of it, potentially by asking friends in China for early testing, when the app is ready for release. Possibly ask Niao.

**Comment by wangwill** [comment]
Can store files on one of my Korean servers.

**Comment by RichardeJiang** [comment]
@wangwill hmm actually using Google's Firestore on purpose because this saves us from writing a backend explicitly / deploying to any server. What I did in the previous 2 commits are just preparing the JSON format in Firestore -> connect with Flutter -> then done. As long as it's connectable from China, there's no need for us to deploy to servers.

**Comment by RichardeJiang** [comment]
We may call it resolved in commit https://github.com/RichardeJiang/from_android/commit/07c2103a2181716f97d99136c18289ce4bafbad8
